CREATE TABLE nomfinder_events (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_name TEXT NOT NULL,
    start_date TIMESTAMPTZ NOT NULL,
    end_date TIMESTAMPTZ NOT NULL,
    event_type TEXT NOT NULL,
    location_address TEXT NOT NULL,
    location_city TEXT NOT NULL,
    location_zipcode INTEGER NOT NULL
);
