CREATE TABLE nomfinder_menu_items (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item_name TEXT NOT NULL,
    item_description TEXT,
    ingredients TEXT,
    vegetarian BOOLEAN DEFAULT FALSE,
    vegan BOOLEAN DEFAULT FALSE,
    vegetarian_option BOOLEAN DEFAULT FALSE,
    vegan_option BOOLEAN DEFAULT FALSE,
    gluten_free BOOLEAN DEFAULT FALSE,
    cost DECIMAL(4,2) NOT NULL,
    menu_category INTEGER DEFAULT 0
	REFERENCES nomfinder_menu_category(id) ON DELETE SET DEFAULT
);
